# ==========================================
# TricraftCore
# ==========================================

server:
  name: "Tricraft"

# ==========================================
# WORLD INVENTORIES
# ==========================================

world-inventory:

  # World inventory systeem aan/uit
  enabled: true

  # Iedere wereld hieronder krijgt een eigen inventory.
  #
  # Hub:
  #   eigen Hub inventory
  #
  # world:
  #   eigen Survival inventory
  #
  # skyblock_world:
  #   eigen Skyblock inventory
  #
  worlds:
    - Hub
    - world
    - skyblock_world


# ==========================================
# ECONOMY
# ==========================================

economy:

  enabled: true

  starting-money: 100.0

  currency: "$"


# ==========================================
# CLAIMS
# ==========================================

claims:

  enabled: true


# ==========================================
# PORTALS
# ==========================================

portals:

  enabled: true


# ==========================================
# NPC
# ==========================================

npc:

  enabled: true


# ==========================================
# SHOP
# ==========================================

shop:

  enabled: true


# ==========================================
# PVP
# ==========================================

pvp:

  enabled: true


# ==========================================
# SKYBLOCK
# ==========================================

skyblock:

  enabled: true


# ==========================================
# VOICE CHAT
# ==========================================

voice-chat:

  enabled: true
